# Generated by Django 5.1.3 on 2024-12-05 14:38

import django.core.validators
import ventasapp.validadores
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasapp', '0002_descuento_metodopago_alter_clientes_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productos',
            options={'verbose_name': 'Producto :', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cedula',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, validators=[ventasapp.validadores.validacion_numeros, django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='productos',
            name='cantidad_stock',
            field=models.IntegerField(validators=[ventasapp.validadores.validacion_numeros], verbose_name='Cantidad en stock : '),
        ),
        migrations.AlterField(
            model_name='productos',
            name='codigo',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MaxLengthValidator(10), ventasapp.validadores.validacion_numeros]),
        ),
        migrations.AlterField(
            model_name='productos',
            name='nombre',
            field=models.CharField(max_length=50, validators=[ventasapp.validadores.Validacion_letras], verbose_name=' Nombre del producto : '),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.DecimalField(decimal_places=2, help_text='ingresa valores con decimales', max_digits=10, validators=[ventasapp.validadores.validacion_numeros], verbose_name='Precio del producto : '),
        ),
    ]
